# Generated by Django 3.2.18 on 2023-02-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('ba968c13-a013-484a-a673-f3f39b632944'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizzacategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('ba968c13-a013-484a-a673-f3f39b632944'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('ba968c13-a013-484a-a673-f3f39b632944'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pizza_name', models.CharField(max_length=100)),
                ('pizza_price', models.IntegerField()),
                ('pizza_image', models.ImageField(upload_to='pizza_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza.pizzacategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart_items',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('ba968c13-a013-484a-a673-f3f39b632944'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='pizza.cart')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
