# Generated by Django 3.2.18 on 2023-02-15 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('68d1df6d-72dd-435d-b45c-5356302421b4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('68d1df6d-72dd-435d-b45c-5356302421b4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('68d1df6d-72dd-435d-b45c-5356302421b4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizzacategory',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('68d1df6d-72dd-435d-b45c-5356302421b4'), primary_key=True, serialize=False),
        ),
    ]
