# Generated by Django 3.2.18 on 2023-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20230215_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_id',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_request_id',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
